# Generated by Django 2.1 on 2018-09-08 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('branch', models.CharField(blank=True, max_length=200, null=True)),
                ('rollno', models.IntegerField(blank=True, default=170, null=True)),
                ('email', models.EmailField(blank=True, max_length=555, null=True)),
                ('phone', models.IntegerField(blank=True, default=200, null=True)),
                ('token', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
