# Generated by Django 2.1.1 on 2018-10-24 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fractalweb', '0002_auto_20180921_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extendeduser',
            name='phone',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
    ]
