# Generated by Django 2.0 on 2018-09-20 20:33

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(max_length=60)),
            ],
            options={
                'ordering': ('session',),
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=200)),
                ('url', models.URLField(blank=True, max_length=555, null=True)),
                ('question_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='classroom.Archive')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=200)),
                ('duration', models.IntegerField(default=0)),
                ('schedule_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=200, null=True)),
                ('url', models.URLField(blank=True, max_length=555, null=True)),
                ('question_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='classroom.Archive')),
            ],
        ),
    ]
